solid/solidproject.org

_posts/this-week-in-solid/2019-12-05-this-week-in-solid..md

added this sub-section, if you like it...
2020-02-07 [This CERN internal event](https://indico.cern.ch/e/CERN-Solid-brainstorming) may bring the place where Sir Tim invented the Web to the heart of the Web's future by Maria Dimou

Update and rename next.md to 2019-12-05-this-week-in-solid..md

---

_posts/for-developers/pod-server/2019-01-01-00_overview.md

as in https://github.com/solid/solid.github.io/pull/244

change recursive option of chmod -R 777 ./live

---

_posts/for-developers/apps/first-app/2019-01-01-00_index.md
_posts/for-developers/apps/first-app/2019-01-01-01_authentication.md
_posts/for-developers/apps/first-app/2019-01-01-02_understanding-solid.md
_posts/for-developers/apps/first-app/2019-01-01-03_reading-data.md
_posts/for-developers/apps/first-app/2019-01-01-04_data-model.md
_posts/for-developers/apps/first-app/2019-01-01-05_writing-data.md

These were suggested by Pat, and look good to me.

Some wording changes to the "first app" tutorial

---

pages/solid-events.md

@Mitzi-Laszlo, I presume the years for these events should be 2020?
(Thanks to @vid for pointing this out.)

Upcoming events are in 2020

---

_posts/for-developers/pod-server/2019-01-01-00_overview.md

@Vinnl @NSeydoux 755 seems sufficient

adjusted file rights for letsencrypt

---

_posts/for-developers/apps/vocabularies/2019-01-01-01_quickstart-creation.md

This addition will help some team members to create a vocabulary from scratch.

Added language tag section in vocab creation quickstart

---

_posts/for-developers/apps/vocabularies/2019-01-01-01_quickstart-creation.md

Just added a paragraph to explain that it's also perfectly fine to have string literals with no language tag at all

Just some further additions and tweaks.

---

_posts/this-week-in-solid/next.md

add my third blog post and info on the 2/20 Bay Area Solid Interest Club meetup

updates for BASIC and Travis

---

pages/use-solid/apps.md

I've suggested new language to include at the top of the app listing page on solidproject.org following the discussion here: https://github.com/solid/solidproject.org/issues/161

Add disclaimer and removal process to app listing

---

_posts/this-week-in-solid/2020-03-26-this-week-in-solid.md

It had already been reviewed, but I'd forgotten to move it from `next.md` into its own post >.<

Actually publish TWiS edition 2020-03-26

---

_posts/this-week-in-solid/2020-04-01-this-week-in-solid.md
_posts/this-week-in-solid/next.md

It's a day early in order to promote tomorrow's Covid19 hackathon and Solid World.

Publish this week's edition of TWiS

---

_posts/for-developers/pod-server/2019-01-01-00_overview.md
pages/faqs.md
pages/for-enterprises.html

This PR fixes some typos, duplicating blocks, and broken links:
* [Setting up a Pod server](https://solidproject.org/for-developers/pod-server)
* [FAQ](https://solidproject.org/faqs)
* [For Enterprises](https://solidproject.org/for-enterprises/)

Fix miscellaneous typos

---

.yaspellerrc
_includes/breadcrumbs.html
_layouts/this-week-in-solid.html
_posts/this-week-in-solid/2019-01-01-this-week-in-solid.md
pages/press.md
pages/this-week-in-solid-archive.md

Automatically display recent TWiS editions

---

pages/faqs.md

in response to questions about vulnerability of "origin", here's an answer

add "origin" escape vulnerability answer

---

.travis.yml

Deploy FAQ about Origin vulnerability

---

pages/home.md

@timbl wanted to use the following as the tagline for the homepage, so this PR adds that:
>  Solid is a technology, like the Web, but a new level of standard which adds to the existing protocols to make it more powerful, particularly to empower individuals at home and at work.
Fixes #239.

Use @timbl's tagline

---

pages/home.md

These bullets were written by Tim for the homepage.
Fixes #238.

Use @timbl's vision description

---

_data/footer.yml

We weren't sure what other links needed to be added to fix #55, other than this one?

Add a link to the App List to the footer

---

pages/standardisation.md

@csarven once you set up Jitsi could you include the link here too

Create an overview of all recurring calls

---

experimental-pods.md

This .md file needs to be included somewhere in the navigation around solidproject.org/for-developers.

Create Experimental Pod Listing for Developers

---

pages/press.md

Originally mentioned on https://github.com/solid/solidproject.org/issues/159

Include Talk

---

pages/press.md

https://github.com/solid/solidproject.org/issues/121

Add Article

---

pages/press.md

Updated press page with content from last edition of the newsletter and added the next edition of the webinar.

Update Press Page

---

_posts/for-developers/pod-server/2020-08-12-00_nginx-config.md

nginx configuration file for reverse proxy and SSL-Configuration
d2020-08-12 t16:47

nginx configuration page

---

pages/press.md

Solid changes the current model where users have to hand over personal data to digital giants in exchange for perceived value.

Update press.md with two Solid articles

---

_posts/for-developers/pod-server/2019-01-01-00_overview.md

@Vinnl @NSeydoux @Mitzi-Laszlo 
3 minor changes: generalize introduction changes, node version 10 needed, chown `config.json` added

minor content changes

---

_includes/footer.html
_includes/header.html

is-hidden-mobile is-paddingless < 0.90 BULMA is-size-7-mobile

responsiveness

---

pages/use-solid.md

Request from @timbl to move solid.community from the experimental to the non-experimental pod listing

Following conversation on https://gitter.im/solid/solidos

---

pages/team.md

Minor bio update re suggestion in https://github.com/solid/solidproject.org/pull/195#discussion_r429154936

Update csarven's bio on team

---

_posts/for-developers/pod-server/2019-01-01-00_overview.md

@Vinnl @NSeydoux @Mitzi-Laszlo 
added -R option

add chown option for contents of directories

---

pages/press.md

Solid changes the current model where users have to hand over personal data to digital giants in exchange for perceived value.

404, wayback null

---

pages/press.md

links links links

---

_posts/newsletter/next.md

Edit to solid-file-client

---

_posts/for-developers/pod-server/2019-01-02-00_apache-config.md

@Mitzi-Laszlo @Vinnl @NSeydoux 
d2020-10-05 t17:10
let's bring this little change on its way to the live-site...

add restart apache to enable changes to config

---

pages/solid-events.md

Add Solid World November Preview

---

pages/use-solid/apps.md

Added Inox to the pod management apps.

Added Inox to the pod management apps.

---

_layouts/for-developers.html

is-pulled-right
button 'improve'
[x] Allow edits by maintainers

improve for-dev

---

_includes/subscribe.html

Changing newsletter signup link from /ThisWeekinSolid to /ThisMonthinSolid

Update newsletter sign-up link

---

_posts/for-developers/pod-server/2019-01-01-00_overview.md

@Mitzi-Laszlo @Vinnl @NSeydoux 
updated documentation on needed nodejs version to 12

Adjust needed nodejs version to 12

---

_includes/subscribe.html

#386 didn't fix all references, so the new link still didn't work.

Fix newsletter signup target

---

_posts/for-developers/apps/tools/2019-01-01-00_overview.md

Added solid-client-authn-js, solid-client-js, updated Solid React SDK to the new repo.

Updated to the latest Inrupt libraries

---

_includes/talk.html

_for talks that are not vsiaul media_ 
[x] Allow edits by maintainers

include.audio

---

pages/team.md

this would be the hardest for the Solid team that @ am sure of, easier for a complete outsider to do
this PR is **not urgent**, just a reflection of the shifts and shuffle so would close immediately after creation. 
to @Mitzi-Laszlo , even tough we have not met, please know that you were one of the firsts (sifting through your commits to the Solidproject) that got me from crawling to walking figuring all this stupid git-scm stuff. Please do forgive me for any wrongdoings done.
[ x ] Allow edits by maintainers

remember the name,

---

pages/press.md

HOW TO FIX THE INTERNET

---

_posts/developers/apps/vocabularies/2019-01-01-00_overview.md
_posts/developers/apps/vocabularies/2019-01-01-01_quickstart-creation.md
_posts/developers/apps/vocabularies/2019-01-01-02_quickstart-publish.md
_posts/developers/apps/vocabularies/2019-01-01-02_quickstart-usage.md
_posts/developers/apps/vocabularies/2019-01-01-04_quickstart-artifacts.md
_posts/developers/apps/vocabularies/2019-01-01-04_well-known.md
_posts/developers/apps/vocabularies/2019-01-01-05_common.md
_posts/developers/apps/vocabularies/2019-01-01-06_technical.md
_posts/developers/apps/vocabularies/2019-01-01-07_core.md
_posts/developers/apps/vocabularies/2019-01-01-08_solid.md
_posts/developers/apps/vocabularies/2019-01-01-09_discover.md
_posts/developers/apps/vocabularies/2019-01-01-10_create.md
_posts/developers/apps/vocabularies/2019-01-01-11_creation-good-practices.md
_posts/developers/apps/vocabularies/2019-01-01-12_extended-creation.md
_posts/developers/apps/vocabularies/2019-01-01-13_creation-methodology.md
_posts/developers/apps/vocabularies/2019-01-01-14_extended-usage.md
_posts/developers/apps/vocabularies/2019-01-01-15_publish.md
_posts/developers/apps/vocabularies/2019-01-01-16_publish-rdf.md
_posts/developers/apps/vocabularies/2019-01-01-17_publish-artifacts.md

insert 'for-' '/apps/'

---

_data/footer.yml
_posts/developers/apps/2019-01-01-00_overview.md
pages/home.md
pages/use-solid.md

Surfaced after running a dead link checker

fix broken links

---

assets/css/main.scss
pages/home.md

This applies some of the changes I added as suggestions in Justin's earlier PR but that weren't incorporated, and adds a couple of other best practices (mainly removing magic constants and not using Bulma's included classes).

Apply styling suggestions

---

pages/solid-events.md

Preview: https://deploy-preview-426--solidproject-dot-org.netlify.app/events

List Solid World December in events

---

_posts/developers/apps/inrupt-tutorial/2020-11-06-00_getting-started.md

Fixes #428.
As first reported here: https://forum.solidproject.org/t/welcome-to-the-official-solid-community-forum/8/2

Add redirect from old "for-developers/apps" page

---

pages/use-solid.md

d 2020-11-22 t09:50
@Vinnl @NSeydoux @melvincarvalho @Mitzi-Laszlo @timbl 
we' d like to get listed as grass roots germany with solidweb.org

Added Solid Grassroots Project solidweb.org

---

pages/press.md

solid talks
[ x ] Allow edits by maintainers

solid nov solid dec

---

_posts/developers/apps/inrupt-tutorial/2020-11-06-00_getting-started.md

Some tweaks to the text of the Getting Started Tutorial

Getting Started Tutorial: tweaks to text

---

_posts/developers/pod-server/2020-08-12-00_nginx-config.md

@Vinnl @NSeydoux 
d2021-01-04 t00:40
set two headers in config, minor change

enable wss://

---

pages/solid-events.md

Upcoming 2020-01-07 Solid world should be 2021-01-07

Fix 2020 typo for Solid Events

---

_posts/newsletter/next.md
pages/press.md

@angelo-v @VirginiaBalseiro pinging you that you both are OK with being listed on the "in the press" page (and for Virginia in the newsletter), and whether the links for your names point to where you'd like them to point.
Press page preview: https://deploy-preview-481--solidproject-dot-org.netlify.app/press (newsletter wouldn't be published yet)

Add recent podcast episodes to the press page and the newsletter

---

_includes/subscribe.html

We hit the Tinyletter limits and have moved to Mailchimp.

Migrate to Mailchipm signup form

---

pages/solid-events.md

- Break up the table.
- Tweak some of the wording.
Rendered view: https://deploy-preview-500--solidproject-dot-org.netlify.app/events

Minor edits to Events page

---

_includes/twis-intro.md
_layouts/for-developers.html
_posts/developers/apps/inrupt-tutorial/2020-11-06-00_getting-started.md
_posts/developers/apps/tools/2019-01-01-00_overview.md
_posts/developers/apps/tools/2020-01-25_overview.md
_posts/newsletter/2019-01-01-this-week-in-solid.md
_posts/newsletter/2019-12-05-this-week-in-solid.md
_posts/newsletter/2020-03-26-this-week-in-solid.md
_posts/newsletter/2020-04-09-this-month-in-solid.md
_posts/newsletter/2020-05-07-this-month-in-solid.md
_posts/newsletter/2020-06-04-this-month-in-solid.md
_posts/newsletter/2021-01-12-this-month-in-solid.md
pages/funding.md
pages/use-solid/apps.md

Todo:
@justinwb Could you verify whether there's something to change on the Netlify side to keep deployments running?

Change references to `master` branch to `main`

---

pages/solid-events.md

https://deploy-preview-519--solidproject-dot-org.netlify.app/events

Add February Solid world recording to events page

---

_data/navigation.yml
_includes/header.html
assets/css/main.scss

I took a best guess at what items should be under Developers and Users.  
https://deploy-preview-518--solidproject-dot-org.netlify.app/

Tweak Header menu: includes dropdown items

---

pages/home.md

Note: This PR replaces #475. 
@kay-kim and I worked on this live together and it was quicker at the time to work from a new local branch.

Revised tweaks to homepage.

---

_posts/developers/apps/tools/2019-01-01-00_overview.md

I created a "hello world" example in Rust, might be useful to share.

Add solid-warp to tools/libraries

---

pages/press.md

Solid world March

---

pages/solid-labs.md

https://deploy-preview-561--solidproject-dot-org.netlify.app/labs

Add BBC R&D to the research labs

---

pages/use-solid/apps.md

I didn't know exactly where to put the entry so feel free to change it before it gets merged

Add drive application

---

pages/team.md

Updated my bio for grammar and wording

Updated Kyra's bio

---

pages/solid-events.md

Adding links to Solid World presenter and topics forms.  
https://deploy-preview-594--solidproject-dot-org.netlify.app/events

add solid world form links

---

_posts/developers/apps/inrupt-tutorial/2020-11-06-00_getting-started.md

This sentence could also be reworded as: “to read and write to your name in your user profile”

Suggestion for minor grammatical change

---

_posts/developers/apps/inrupt-tutorial/2020-11-06-00_getting-started.md

This also removes some trailing whitespace but can put that back in if you want.

Update links in getting started tutorial

---

pages/solid-events.md

https://deploy-preview-604--solidproject-dot-org.netlify.app/events

Add Solid World June recording and August listing

---

_posts/developers/apps/vocabularies/2019-01-01-04_quickstart-artifacts.md

Add link to artifact generator and update script to generate files.

Add link to artifact generator and update script to generate files in 2019-01-01-04_quickstart-artifacts.md

---

_posts/developers/apps/tools/2019-01-01-00_overview.md

Swift-based authentication for a Solid Pod

Add entry for SolidAuthSwift

---

_posts/newsletter/2019-01-01-this-week-in-solid.md
_posts/newsletter/2021-08-12-this-month-in-solid.md

- Clean up TMIS landing page.
- Add sections to TMIS newsletter.

Tmis add format

---

pages/team.md

I've changed jobs but will stay with the community, so here's an update with what I'm doing now.

Update Kjetils affiliation

---

_posts/developers/apps/inrupt-tutorial/codesandbox/index.html

Fix HTML for in codesandbox form label

---

_posts/developers/pod-server/2019-01-01-00_overview.md

Added ESS and TrinPod as of Tim's request

added enterprise Solid servers

---

pages/use-solid.md

Added use.id to the list of pod providers.

Add use.id to list of pod providers

---

pages/use-solid.md

d2022-08-28 t10:47
added experimental Pod-Provider (currently >=75 users in production)

add solidweb.me to list of Pod-Providers

---

pages/use-solid/apps.md

An implementation of the decisions made in this Pull Request: https://github.com/solid/team/issues/28

Update Apps Page 2022

---

pages/about.md
pages/contributing.md
pages/team.md

Fix: typos

---

pages/team.md

Timea and Alain were added as admins. Long overdue change.

Updated team list

---

pages/use-solid.md

Add iGrant.io Data Pod to list of pod providers

Add iGrant.io Data Pod to list of pod providers

---

pages/team.md

Aligning on the work over on https://github.com/solid/team/issues/33
@TallTed could you please add a bit of a description about yourself.

removed Nic A.S. and added Ted

---

pages/use-solid/apps.md

Fix broken table formatting in markdown file

---

_data/navigation.yml

This should fix: https://github.com/solid/solidproject.org/issues/781

Gitter link change

---

pages/use-solid.md

d2023-05-22 t04:10
add experimental / production Pod Provider

add https://solid.redpencil.io/ to Pod Providers

---

pages/team.md

Long overdue: moved myself (Timea) from admin to creator.

Changed Timea's role

---

_posts/developers/apps/inrupt-tutorial/2021-08-03-00_getting-started.md

I think it would be a good information, that there's a Rust server in development by @damooo, so I would add it to the list. Would you be fine with this, @damooo?
I've added the "in alpha stage" comment, as it is self described as such. It's a draft PR to wait for their response.

Add manas to server list

---

_data/navigation.yml

Renamed chat and changed link:  https://matrix.to/#/#solid_project:matrix.org

changed chat link

---

pages/use-solid/apps.md

Found from https://forum.solidproject.org/t/booklice/4464

Add Booklice

---

pages/use-solid/apps.md

Found from https://forum.solidproject.org/t/webclip/4730

Add WebClip

---

pages/solid-events.md

Not sure if "COST / VITO" is correct for "organiser", improvements welcome.

Add SoSy 2024

---

README.md

Explain use of file URLs

---

about.html
community.html
for-developers.html
for-organizations.html
index.html
terms.html

Saw that some links were missing URLs, and also changed some URLs based on feedback from Kyra.

Adding and changing some URLs

---

about/index.html
apps/index.html
contributing/index.html
developers/index.html
developers/tools/index.html
developers/tutorials/getting-started/index.html
developers/tutorials/index.html
developers/vocabularies/index.html
events/index.html
newsletter/index.html
press/index.html
specification/index.html
team/index.html
users/get-a-pod/index.html
users/index.html

Some resources are removed altogether though, and I don't know where to point to on the new website.

Added stubs to ensure old URIs for old website

---

about.html
community.html
for-developers.html
for-organizations.html
for-users.html
index.html
style/base.css
terms.html

Resolves https://github.com/solid/solidproject.org/issues/859
for-users links to existing pages:
* https://solidproject.org/users/get-a-pod
* https://solidproject.org/apps

Add for-users page

---

for-developers.html

@-maintainers-
d2024-06-03 txy:56

update reference redpencil

---

about.html

Thanks for [flagging this](https://forum.solidproject.org/t/solid-project-website-update/7484/7?u=michielbdejong) @ewingson!

Remove duplicate paragraph on about.html

---

for-organizations.html

link correct link text missing letter "a" in athumi

---

community.html
for-organizations.html

Fixes markup to be valid.
Aside: The script that was used to generate some parts of the markup may need to revisited if it is used in the future because it is generating invalid markup in some parts, e.g., event dates.

Fix markup in community and for-organizations

---

for-developers.html

I have added links to the documentations of the available servers
d2024-06-16 t14:01

update available server implementations with current links to public docs

---

users/get-a-pod.html

d2024-07-23 t12:26
@michielbdejong
I have added Solid Community AU

add solid community AU to historical site (still online)

---

community.html
for-organizations.html
for-users.html
index.html
style/base.css
terms.html

Adding pointers to this announcement https://forum.solidproject.org/t/a-new-organisational-home-for-solid/8004

add new organisational home

---

for-organizations.html

d2024-10-06 t04:03
I have updated the organizations with meisdata, our open collective

add meisdata (open collective)

---

for-developers.html
style/base.css

https://github.com/solid/solidproject.org/issues/909

Add specification links to ForDevelopers page

---

for-developers.html

d2025-02-22 t18:53
discoverablity improved

replace deeplinks with link to server root

---

for-developers.html
users/get-a-pod.html

d2025-02-25 t07:36
@jeswr hope that helps,
minor lacking attentiveness removed, two changes

two minor changes: a hrefs in services page, css to pivot in get-a-pod

---

apps.html

Move non-functional apps into 'historical' section

---

community.html
events.html

Add 'allow-downloads' permission to the iframe sandbox to fix "ADD TO MY CALENDAR" button functionality on the calendar.

Fix: enable 'add to my calendar' button in iframe
