- _posts/this-week-in-solid/2019-01-01-this-week-in-solid.md
- _posts/this-week-in-solid/2019-10-31-this-week-in-solid.md
- _posts/this-week-in-solid/2019-11-07-this-week-in-solid.md
- _posts/this-week-in-solid/2019-11-14-this-week-in-solid.md
- _posts/this-week-in-solid/next.md
The pages were at /weekly-updates, isntead of /this-week-in-solid.
Additionally, the link to submit a pull request was pointing to the
solid.github.io repo, while TWiS is being compiled on the
solidproject.org repository.
(Note that the rest of development on the website still happens
on the solid.github.io repository.)
> Fix This Week in Solid links

- pages/home.md
These two links currently result in a 404 since `/specification` doesn't exist.
I'm not actually sure what the right location is, but since the same paragraph links to `/standardisation` as well, I *assume* the others should link to the specification.
Let me know if I should change anything or feel free to close it if you have a better solution.
> Fix link to specification on home page

- pages/home.md
The current homepage copy is inaccurate regarding the relation between Solid and standards/specifications. We should be careful to not spread misinformation.
This PR replaces the current version with a text that is technically accurate. Changes to phrasing etc. are definitely welcome; we just need to ensure that what we write down is truthful.
Once this PR is accepted, I will open a PR to adjust other places (such as the "This week in Solid" newsletter opening copy accordingly), to avoid further spread of the inaccurate version.
-----
**Q1: Why is Solid not a standard?**
Solid operates under a W3C Community Group. W3C states the following regarding its standards:
> W3C publishes Recommendations, which are considered Web standards.
> W3C also publishes **other technical reports that are …
> Rewrite standards copy for accuracy

- _posts/for-developers/apps/tools/2020-01-25_overview.md
The tools page looks great @jeff-zucker. However, I'm not maintaining [solid-lib-comparison](https://github.com/inrupt/solid-lib-comparison) - it was merely a dump of a live coding demo at a meetup, and is now archived. I'd propose [my cheatsheet](https://vincenttunru.gitlab.io/tripledoc/docs/cheatsheet) to serve as a comparison, as I'm actually maintaining that. What do you think?
> Replace archived repo with maintained cheatsheet

- _posts/this-week-in-solid/2019-10-31-this-week-in-solid.md
- _posts/this-week-in-solid/2019-11-07-this-week-in-solid.md
- _posts/this-week-in-solid/2019-11-14-this-week-in-solid.md
- _posts/this-week-in-solid/2019-11-28-this-week-in-solid.md
- _posts/this-week-in-solid/next.md
- pages/press.md
- pages/solid-events.md
Apparently they moved their website to pldn.nl from pilod.nl, which is why our automated checks for broken links are failing...
> Fix changed PLDN links

- pages/press.md
It results in 404 and is not available in the Web Archive: http://web.archive.org/web/*/https://apibestinclass.com/what-is-solid-decentralized-web-tim-berners-lee-is-up-to-something-again/
> Remove broken "API Best in Class" link

- pages/press.md
It was basically a rehash from an article that was already listed,
i.e. https://www.bbc.com/news/business-47027072. It's also been taken down, causing the build to fail.
> Remove redundant article

- _data/footer.yml
To make it clear where people can direct feedback on the website, this adds a link to the footer directing people to GitHub issues.
> Add link to GitHub issues for website feedback

- .travis.yml
This will prevent our builds from suddenly failing if yaspeller
e.g. (purely hypothetically *cough*) adds a fuzzier typo checker.
Note: it's not hypothetical, our build is currently broken because yaspeller is apparently interpreting `**WebID** is` as `WebID  is` (i.e. with two spaces), which is something different from the word in our dictionary (`WebID is`).
We could work around that some time, but at a time of our choosing, rather than the build suddenly breaking while we were working on other things. Hence, the locked version.
> Lock the yaspeller version

- .travis.yml
I'm getting really tired of htmlproofer failing the build due to links that are yet to be deployed erroring, even though we cannot deploy because the build fails. Hence, I've suppressed failing exit codes for HTML proofer: we can still see the warnings, but they won't block the build.
> Do not fail the build if htmlproofer fails

- pages/faqs.md
- The two duplicate FAQs removed are those with the missing
comma and the spelling mistake ('of' vs 'or').
> These two FAQs appear twice. Removing one copy.

- pages/use-solid/apps.md
Include the Solid Geolocation Challenge app entries and change the name of the vertical from Navigation to Geolocation to avoid confusion with the technical term.
> Include Apps and Change Vertical

- pages/funding.md
The order of entries on the funding page seems a bit [hodge-podge](https://en.wikipedia.org/wiki/Hodge-podge).
This merge-request remedies that by sorting them in alphabetical order.
> Sort entries on the funding page alphabetically

- pages/use-solid.md
https://solid.authing.cn is resulting in a 504 Gateway Time-out error page. With this pull request, I propose to de-list the Pod provider until the link is repaired.
> Pod Provider Link not Loading

- pages/press.md
The `|` in the text made Jekyll think that it was a table row, which it was not:
> Fix syntax error in press listing

- _posts/newsletter/2020-09-03-this-month-in-solid.md
This edition needs a specification update from the editors, or for that section to be removed. 
The link for Solid World September will be included after the webinar. 
@KaiGilb if you have any further editions to the news on TrinPod then this would be the place to include it.
> New edition of newsletter

- pages/implement.md
- pages/use-solid.md
- pages/use-solid/apps.md
- website-strategy.md
I've noticed some legacy urls that are not redirecting property, in particular this one: https://solidproject.org/use-solid/
There is an issue with Github Pages, because that url works properly running the site locally. The solution is to declare the `redirect_from` with a trailing slash, like it's already done with this url that isn't broken: https://solidproject.org/for-developers/
While I was at it, I've fixed some typos and removed some trailing whitespace :D (my editor settings do that automatically).
> Fix legacy url redirects and typos

- _posts/developers/pod-server/2019-01-01-00_overview.md
d2020-11-13 t21:24
@Vinnl @NSeydoux
the `solid init` codeblock was black.
the config statement should have fixed that.
> make solid init config viewable

- _sass/rouge-themes/monokai.scss
It was turned black, which isn't great on a black background.
Fixes #419.
Compare step 6: [before](https://solidproject.org/developers/tutorials/getting-started) and [after](https://deploy-preview-421--solidproject-dot-org.netlify.app/developers/tutorials/getting-started).
> Make code colour white by default

- pages/about.md
In the about page > getting involved section, organized the various call to actions  in a list so that the links are easier to click.
https://deploy-preview-477--solidproject-dot-org.netlify.app/about#how-can-i-get-involved
> Tweak How can I get involved section

- pages/solid-events.md
Ugh - that dangling modifier ("to meet" at the end of the first sentence) -- I thought I could live with it (so that the site is a bit less formal) - but it just kept nagging at me -- as though it was modifying "people are interested in Solid to meet".  We all have our idiosyncrasies - sigh :(
> small grammar fix to solid-events page

- _posts/developers/apps/tools/2019-01-01-00_overview.md
solid-flask is currently very bare-bones, but it does implement basic required DPoP auth, which I didn't find implemented anywhere else in Python. If there's anyone else who wants to develop for Solid in Python, it might serve as an okay starting point.
> Add link to solid-flask to developer tools

- _posts/developers/apps/tools/2019-01-01-00_overview.md
This is a Perl module to authenticate against Solid-OIDC and provides a command line tool to add DPoP authentication headers to curl.
> Adding the Web::Solid::Auth tool

- _data/footer.yml
- pages/terms.md
This is an initial PR for the Terms page as per https://github.com/solid/solidproject.org/issues/437 .
It includes information about the URI Persistence Policy as per https://github.com/solid/solidproject.org/issues/247 . It is a pledge to have persistence for Solid technical reports published under `https://solidproject.org/TR/` (eg. https://github.com/solid/solidproject.org/issues/249 )
IANAL, so, perhaps best to start by addressing the type of Terms ie. "Terms of Use" or "Terms of Service" or "Terms and Conditions", or possible others. This PR uses: "Terms of Use".
Proposed path for the Terms resource is `https://solidproject.org/terms` -- but open to alternatives.
I propose that additional information about the Terms is made in subsequent PRs.
> Init Terms page including URI Persistence Policy

- _posts/developers/apps/tools/2019-01-01-00_overview.md
This is a simple app illustrating how to implement Solid OIDC using Spring, and may serve as a useful point of reference for anyone else looking to build a Solid app in the Java/Kotlin ecosystem.
> Adds link to spring-solid-demo

- Gemfile
- Gemfile.lock
- _config.yml
We have quite a few places where we're listing email address in a Markdown file, but have not explicitly turned them into a link. This plugin does that automatically for us. (We couldn't add that on GitHub Pages, but now that we're on Netlify, we're free to use any plugin we want :)
Compare e.g. https://deploy-preview-614--solidproject-dot-org.netlify.app/apps with https://solidproject.org/apps at the bottom of the page, where it says:
> Want to add an eligible Solid-compatible app to this list? Contact the Solid Manager via info@solidproject.org or submit a pull request.
> Add autolink-email plugin

- _posts/developers/apps/vocabularies/2019-01-01-04_quickstart-artifacts.md
Removed "LIT" from the artifact generator name + mark as Alpha + minor tweaks to remove unnecessary words like "nice" and "easily" and "simply"
https://deploy-preview-620--solidproject-dot-org.netlify.app/developers/vocabularies/code/quickstart#the-artifact-generator
> trivial: remove LIT prefix to artifact generator

- _posts/developers/apps/vocabularies/2019-01-01-02_quickstart-usage.md
Found a little typo while reading the tutorials!
> Fix typo in vocabularies quickstart usage page

- _posts/developers/apps/inrupt-tutorial/2020-11-06-00_first-app.md
Two other links in the API documentation returned a 404 (File not found).
These links appear to be case sensitive.
> Fixed typo in links to API Documentation

- _posts/developers/apps/inrupt-tutorial/2020-11-06-00_first-app.md
I thought this note might be useful after misunderstanding [how to use Solid](https://forum.solidproject.org/t/net-c-dotnetrdf-for-solid/1687).
Specifically, a few weeks ago, when I was trying to get back into Solid, I was under the impression that the only real way to work with Solid was to use the JavaScript libraries, and set about trying to understand how Solid worked in order to go about building a specific .NET client library to interact with Solid pods.
After awhile, it dawned on me: It would be nice if up front it was clear that Solid is built on top of open standards, which many platforms (i.e. Python, .NET, PHP, etc.) already have libraries for standards that Solid implements (RDF, HTTP, OpenID Connect, etc). Thus you don't need the Inrupt JavaScript libraries to get started - …
> Solid uses open standards

- .gitignore
This MR removes non-project things from the `.gitignore` file, such as OS and IDE specific files.
As requested by @kjetilk in https://github.com/solid/solidproject.org/pull/160#issuecomment-596570532.
Fixes  #162
>  Remove editor-specific things from .gitignore

- _posts/developers/apps/tools/2019-01-01-00_overview.md
Adds [Solid Client PHP](https://github.com/dunglas/solid-client-php) (see also [the related presentation](https://dunglas.fr/2022/04/building-decentralized-web-apps-with-solid-and-php/)).
> Libraries: add Solid Client PHP

- pages/solid-events.md
As found on [Angelo Veltens' Mastodon](https://social.veltens.org/@angelo/109767787513814185).
Preview: https://deploy-preview-763--solidproject-dot-org.netlify.app/events
> Add the Nürnberg Solid symposium 2023

- _data/footer.yml
- _data/navigation.yml
- _includes/toc-about.html
- pages/funding.md
- pages/implement.md
- pages/job-board.md
- pages/origin.md
- pages/solid-labs.md
Per [earlier May 24 meeting discussion](https://github.com/solid/team/blob/main/meetings/2023-05-24.md) -- 2nd part of the initial cleanup:
- Archive the funding page to the wiki and redirect to the wiki.
- Redirect the implement page and redirect to the home page.
- Archive the research labs page to the wiki and redirect to the wiki.
- Remove the origin page and redirect to the parent about page.
- Cleanup of footer/toc/menu for the removed/archived pages
> reorg-part2: remove/redirect older pages

- _posts/developers/apps/tools/2019-01-01-00_overview.md
I've added the solid-oidc-py and solid-client-credentials-py libraries to the developer tools list. The solid-oidc-py library is still unstable, the solid-client-credentials-py should be pretty stable. But I think both could be useful for people looking there :)
> Add python authentication libraries

- pages/home.md
This is a proposal for issue #813.
> Replace people by individuals and groups

- developers/tutorials/getting-started.html
Two links in the getting-started page are broken:
- Link to the LDO tutorial
- Link to "Edit on Github"
> Updated links in getting-started section

- about.html
- community.html
- for-developers.html
- for-organizations.html
- for-users.html
- index.html
- terms.html
Updated the following files:
- about.html
- community.html
- for-developers.html
- for-organizations.html
- for-users.html
- index.html
- terms.html
- clear path to technical support
- Verified locally, appears correctly on all updated pages.
> Add support link to site pages

- _redirects
The redirect rule removed by this PR pointed https://solidproject.org/TREE/ to https://solid.github.io/specification/tree/protocol-v0.9.0/ (which does not exist anymore).
There is no other link to `/TREE/` under solidproject.org and any link existing elsewhere would have been giving `404` [for over 4 years](https://github.com/solid/specification/commit/ab077628e52efb9daa7fe9b3685e8e4e44f987df).
The Shape Trees spec now lives under its own domain https://shapetrees.org/TR/specification/.
For those reasons, the correct course of action is to remove this redirect.
> Remove broken redirect

- users/get-a-pod.html
d2025-09-19 t11:31
remove https://inrupt.net and https://dev.inrupt.net from overview table because these two instances do not exist anymore
> remove inrupt.net and dev.inrupt.net from table (no more live)

- for_developers.html
Add a link to the [Solid Developers documentation](https://dev.solidproject.org/).
See: https://deploy-preview-939--musical-sawine-26ffa9.netlify.app/for_developers#solid_developers_documentation
> Solid developers documentation link
